require 'scott.packer'
require 'scott.options'
require 'scott.keymaps'
require 'scott.colorscheme'
require 'scott.lualine'
require 'scott.comment'
require 'scott.indent_blankline'
require 'scott.gitsigns'
require 'scott.telescope'
require 'scott.treesitter'
require 'scott.lsp'
require 'scott.bufferline'
require 'scott.nvimtree'
require 'scott.autopairs'
require 'scott.null-ls'

